name: Add Text to PR Description

on:
  pull_request:
    branches:
      - '*'
    types: [opened]

jobs:
  add-text:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Add Text to PR Description v2
      uses: actions/github-script@v4
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const textToAdd = 'Кухаренко Ярослав Ильич 221-322';
          const newDescription = textToAdd;
          github.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            body: newDescription
          });
